services:
  - type: web
    name: healthcare-portal
    runtime: python
    rootDir: healthcare_portal
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn healthcare_portal.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
